sudo: false
language: php
php:
  - 5.5
env:
  - MAGENTO_VERSION=magento-ce-1.9.0.1

services:
  - mysql

install:
  # install composer
  - wget -O composer-setup.php https://getcomposer.org/installer
  - php composer-setup.php --filename=composer

  # install modman
  - bash < <(wget -q --no-check-certificate -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
  - modman --version

  # install n98-magerun
  - wget https://files.magerun.net/n98-magerun.phar
  - chmod +x n98-magerun.phar
  - ./n98-magerun.phar --version

# configure our database and install magento
before_script:
  # clean mysql database
  - mysql -e "DROP DATABASE IF EXISTS magento_test; CREATE DATABASE IF NOT EXISTS magento_test;" -uroot
  # install Magento
  - echo "install magento"
  - rm -rf magento/
  - ./n98-magerun.phar install --magentoVersion "$MAGENTO_VERSION" --installationFolder="magento" --dbHost=“127.0.0.1” --dbUser=“root” --dbPass=“” --dbName="magento_test" installSampleData=no --useDefaultConfigParams=yes --baseUrl="http://magento.localdomain/"
  - cd magento
  - # install dependencies
  - # install module

script:
  - cd magento
