sudo: false
language: php
php:
  - 5.5
env:
  - MAGENTO_VERSION=1.9.2.3

services:
  - mysql

install:
  # clean up
  - echo $TRAVIS_BUILD_DIR
  - rm -rf build; mkdir build;
  - cd build

  # install composer
  - wget -O composer-setup.php https://getcomposer.org/installer
  - php composer-setup.php --filename=composer
  - ./composer --version

  # install modman
  - bash < <(wget -q --no-check-certificate -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
  - modman --version

  # install n98-magerun
  - wget https://files.magerun.net/n98-magerun.phar
  - chmod +x n98-magerun.phar
  - ./n98-magerun.phar --version

before_script:
  # Clean mysql database
  - mysql -e "DROP DATABASE IF EXISTS magento_test; CREATE DATABASE IF NOT EXISTS magento_test;" -uroot

  - cd $TRAVIS_BUILD_DIR/build

  # Download Magento (n98-magerun links are broken)
  - curl https://codeload.github.com/OpenMage/magento-mirror/tar.gz/$MAGENTO_VERSION
  - tar xz; mv magento-mirror-$MAGENTO_VERSION magento

  # Install Magento
  - ls -al; ls -al magento
  - ./n98-magerun.phar install --installationFolder "magento" --dbHost "127.0.0.1" --dbUser "root" --dbPass "" --dbName "magento_test" --baseUrl "http://testmagento.local" --noDownload --forceUseDb yes --useDefaultConfigParams yes

  # Configure
  # install dependencies
  - cd $TRAVIS_BUILD_DIR/build/magento
  - ../modman init
  - ../modman clone git://github.com/EcomDev/EcomDev_PHPUnit.git
  - ls -al ../../
  - modman link ../../
  - ../n98-magerun.phar sys:modules:list | grep -e 'Sheep\|EcomDev_PHPUnit'
  - ls -al


script:
  - cd magento
