sudo: false
language: php
php:
  - 5.5
env:
  - MAGENTO_VERSION=magento-ce-1.9.0.1

services:
  - mysql

before_install:
  # re-create database
  - mysql -e "DROP DATABASE IF EXISTS magento_test; CREATE DATABASE IF NOT EXISTS magento_test;" -uroot

install:
  # install composer
  - wget https://getcomposer.org/installer -O
  - wget -O composer-setup.php https://getcomposer.org/installer
  - php composer-setup.php --filename=composer

  # install modman
  - bash < <(wget -q --no-check-certificate -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
  - modman --version

  # install n98-magerun
  - wget https://files.magerun.net/n98-magerun.phar
  - chmod +x n98-magerun.phar
  - ./n98-magerun.phar --version

# configure our database and install magento
before_script:
  # install magento
  - ./n98-magerun.phar install --dbHost=“127.0.0.1” --dbUser=“root” --dbPass=“” --dbName="magento_test" installSampleData=no --useDefaultConfigParams=yes --magentoVersionByName=“${MAGENTO_VERSION}” --installationFolder="magento" --baseUrl="http://magento.localdomain/"

script:
  - ls -al
