sudo: false
language: php
php:
  - 5.5
env:
  - MAGENTO_VERSION=1.9.2.3

services:
  - mysql

install:
  # clean up
  - echo $TRAVIS_BUILD_DIR
  - rm -rf build; mkdir build;
  - cd build

  # install composer
  - wget -O composer-setup.php https://getcomposer.org/installer
  - php composer-setup.php --filename=composer
  - ./composer --version

  # install phpunit
  - wget -O phpunit https://phar.phpunit.de/phpunit-old.phar
  - chmod +x phpunit
  - phpunit --version

  # install coveralls
   - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
   - chmod +x coveralls.phar

  # install modman
  - bash < <(wget -q --no-check-certificate -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
  - modman --version

  # install n98-magerun
  - wget https://files.magerun.net/n98-magerun.phar
  - chmod +x n98-magerun.phar
  - ./n98-magerun.phar --version

  - export PATH=$PWD:$PATH

before_script:
  # Clean mysql database
  - mysql -e "DROP DATABASE IF EXISTS magento_test; CREATE DATABASE IF NOT EXISTS magento_test;" -uroot

  - cd $TRAVIS_BUILD_DIR/build

  # Download Magento (n98-magerun links are broken)
  - curl https://codeload.github.com/OpenMage/magento-mirror/tar.gz/$MAGENTO_VERSION | tar xz;
  - mv magento-mirror-$MAGENTO_VERSION magento

  # Install Magento
  - n98-magerun.phar install --installationFolder "magento" --dbHost "127.0.0.1" --dbUser "root" --dbPass "" --dbName "magento_test" --baseUrl "http://testmagento.local" --noDownload --forceUseDb yes --useDefaultConfigParams yes
  - mkdir -p magento/var/log

  # Install our module
  - cd $TRAVIS_BUILD_DIR/build/magento
  - modman init
  - modman link $TRAVIS_BUILD_DIR

  # Install EcomDev_PHPUnit
  - modman clone git://github.com/EcomDev/EcomDev_PHPUnit.git
  - cd shell
  - php ecomdev-phpunit.php -a magento-config -r --db-name "magento_test" --same-db true --base-url "http://testmagento.local"

  - n98-magerun.phar sys:modules:list | grep -e 'Sheep\|EcomDev_PHPUnit'


script:
  - cd $TRAVIS_BUILD_DIR/build
  - mkdir logs

  - cd $TRAVIS_BUILD_DIR/build/magento
  - phpunit --group Sheep_Debug --coverage-clover ../logs/clover.xml
  - ls -al ../logs/

after_success:
  - cd $TRAVIS_BUILD_DIR/build
  - ls -al logs
  - ./coveralls.phar -x logs/clover.xml
